module.exports = {
  siteName: 'Zeiq',
  author: 'Parminder Klair',
  description: 'Official Website for Zeiq.co',
  siteUrl: 'https://www.zeiq.co',
  mediumPublicationUrl: 'https://medium.com/zeiq',
  image: './img/zeiq-logo.png',
  googleAnalytics: '',
  backgroundColor: '#e0e0e0',
  themeColor: '#634ce9',
  twitter: '@Zeiqofficial',
  fbAppId: '@zeiq',
  locale: 'en_us',
  type: 'website',
};
