module.exports = {
  siteName: 'Zeiq',
  author: 'Parminder Klair',
  description: 'Official Website for Zeiq.co',
  siteUrl: 'https://www.zeiq.co',
  image: '/img/zeiq-logo.png',
  googleAnalytics: '',
  backgroundColor: '#e0e0e0',
  themeColor: '#c62828',
  twitterSite: '@zeiq',
  twitterCreator: '@zeiq',
  fbUserId: 'fbUserId',
  fbAppId: 'fbAppId',
  locale: 'en_us',
  type: 'website',
};
